// Relative imports only: the tests load this through Node's type stripper.

/**
 * Every word in /play.
 *
 * Plain strings only — no functions — because the page renders on the server
 * and hands this to a client component as a prop, and a function cannot cross
 * that boundary. Anything that needs a number in it uses a `{placeholder}`
 * filled by `fill()`. Traditional Chinese is this object converted on the
 * server, the same way the rest of the site does it.
 *
 * The facts about places and animals are real and were checked; the people in
 * the story are not real, and nor is the golden ibis.
 */

const zh = {
  meta: {
    title: "悉尼周四奇遇 · 像素游戏 · Vibe Thursday",
    description:
      "一个像素风的悉尼：从环形码头走到歌剧院，徒步过海港大桥，坐北岸线火车去 Chatswood，在周四集市逛社区成员做的东西，最后赶上周四上午 10:30 的那张桌子。多人在线，手机能玩。",
  },
  title: "悉尼周四奇遇",
  subtitle: "Vibe Thursday · 像素 RPG",
  tagline: "街道来自真实地图。走到歌剧院，过桥，坐火车去 Chatswood，周四上午 10:30 找到那张桌子。",
  start: "开始",
  continue: "继续冒险",
  newGame: "重新开始",
  loading: "正在铺悉尼的街道…",
  osm: "地图数据 © OpenStreetMap 贡献者",
  saveNote: "进度存在这台设备的浏览器里。",

  create: {
    title: "你是谁",
    hint: "随便捏，之后在衣柜里还能换。",
    skin: "肤色",
    hair: "发型",
    hairColor: "发色",
    top: "上衣",
    bottom: "下装",
    acc: "配饰",
    go: "出发去环形码头",
    random: "随机",
  },

  hud: {
    online: "{n} 人在线",
    offline: "单机模式",
    quest: "任务",
    bag: "收集",
    wardrobe: "衣柜",
    emote: "表情",
    map: "地图",
    close: "关闭",
    a: "A",
    talk: "对话",
    look: "看看",
    board: "上车",
    ferry: "坐渡轮",
    read: "看告示",
    befriend: "交朋友",
    visit: "逛逛",
    you: "你",
    here: "现在位置",
    streak: "连续 {n} 天",
    thursday: "今天是周四！金色白鹮出没中",
    done: "主线完成",
  },

  toast: {
    stamp: "盖章：{name}",
    shard: "找到 Vibe 碎片（{n}/{total}）",
    critter: "交到新朋友：{name}",
    hat: "解锁新帽子：{name}",
    quest: "任务完成：{name}",
    streak: "连续第 {n} 天来悉尼",
    joined: "{name} 来了",
    tooFar: "太远了，先走近一点",
    saved: "已保存",
    rejoin: "重新连上了",
  },

  quests: {
    arrive: { title: "码头上的第一句话", hint: "在环形码头找渡轮水手 Mina 聊聊。" },
    muse: { title: "你在做什么", hint: "去歌剧院前的台阶，找那个街头艺人。" },
    wharf: { title: "码头告示板", hint: "回到环形码头，看告示板上大家卡住的问题（{have}/{need}）。" },
    bridge: { title: "走过衣架桥", hint: "沿着海港大桥的人行道一路往北，走到 Milsons Point 车站。" },
    train: { title: "北岸线", hint: "在 Milsons Point 坐 T1 北岸线去 Chatswood。" },
    market: { title: "周四集市", hint: "在 Chatswood Mall 的集市逛 {need} 个摊位（{have}/{need}）。" },
    people: { title: "找到同频的人", hint: "在 Chatswood 跟 {need} 位成员打个招呼（{have}/{need}）。" },
    thursday: { title: "周四上午 10:30", hint: "去 465 Victoria Avenue 的 The Avenue，那栋圆楼。" },
    allDone: "主线全部完成。去收集图鉴、印章和碎片吧——或者，下周四真的来一趟。",
  },

  ideas: {
    app: "一个 App / 网站",
    content: "内容 / 自媒体",
    shop: "一门生意",
    automation: "自动化 / 工作流",
  },

  npc: {
    deckhand: {
      name: "Mina · 渡轮水手",
      first: [
        "欢迎来到环形码头！绿黄相间的那些就是悉尼渡轮，全港都从这儿出发。",
        "脑子里揣着半个想法来悉尼？大家都是这么来的。",
        "先去歌剧院那边的台阶，有个弹琴的，他问每个人同一个问题。",
      ],
      later: ["想去对岸？码头上的渡轮牌子点一下，直接开到 Milsons Point。", "下一步：{hint}"],
    },
    busker: {
      name: "Leo · 街头艺人",
      ask: ["（一段吉他）……嘿，你在做什么东西？"],
      reply: {
        app: "App 啊。先做出一个能点的版本，比写十页计划书有用。",
        content: "做内容的人最懂人。你会在周四那张桌子上找到你的第一批读者。",
        shop: "做生意的！会用 AI 的老板，比会写代码的人还少。",
        automation: "自动化——把一件烦人的事做到再也不用想它，这是最好的起点。",
      },
      after: ["回码头看看那块告示板，大家把卡住的问题都钉在上面。", "{hint}"],
    },
    climber: {
      name: "Sam · 爬桥的人",
      lines: [
        "这座桥 1932 年通车，悉尼人叫它「衣架」。",
        "人行道一直通到北岸。尽头就是 Milsons Point 车站，坐 T1 去 Chatswood。",
      ],
    },
    guard: {
      name: "Priya · 车站职员",
      lines: ["T1 北岸线，往北六站到 Chatswood：North Sydney、Waverton、Wollstonecraft、St Leonards、Artarmon，然后就到了。"],
      board: "上车去 Chatswood",
      stay: "再逛逛",
    },
    stallholder: {
      name: "Grace · 集市摊主",
      lines: [
        "Chatswood Mall 每到周四都有集市。",
        "今天这几个摊位有点特别：都是周四那桌上的人自己做的东西。逛逛，喜欢就点进去看看。",
      ],
      empty: "今天摊位还没摆出来——等社区里有人把作品挂上成员卡，这里就会有摊位。",
    },
    host: {
      name: "主持人",
      lines: [
        "你找到了！就是这儿：The Avenue，465 Victoria Avenue，Brown St 和 Railway St 转角那栋圆楼。",
        "每周四上午 10:30，一群在做东西的人围一张桌子，聊各自在用 AI 干什么、卡在哪。",
        "想给大家看点东西可以，只来听也完全没问题。免费，不售票。",
      ],
      demo: "轮到你了。你想怎么介绍你在做的东西？",
      demoChoices: ["打开电脑直接演示", "讲讲卡在哪", "先听大家的"],
      demoReply: [
        "屏幕一亮，桌上三个人凑了过来。有人问：你这个上线了吗？",
        "你刚说完卡在哪，对面的人就说：这个我踩过，散场后细聊。",
        "你听了一上午，记了半页纸。最后有人问你：下周你来讲讲？",
      ],
      ending: "这就是周四。游戏里的桌子到这儿就结束了——真的那张，每周四都在。",
      signup: "报名下周四",
      claim: "认领我的成员卡",
      wharf: "去码头回答问题",
      later: ["每周四 10:30，The Avenue。下周见。"],
    },
    noticeboard: {
      name: "码头告示板",
      intro: "大家把卡住的问题钉在这里。点开一条读读看；你答得上来的话，去码头页面帮一把。",
      empty: "告示板今天是空的。下面是示例：",
      examples: ["没有技术背景的人，怎么开始用 AI？", "内容做了半年没起色，问题出在哪？", "小生意从哪一步开始数字化？"],
      by: "来自 {name}",
      example: "示例",
      open: "去码头回答",
    },
    barista: {
      name: "Nico · 咖啡车",
      offer: ["今天集市人多，好几个熟客在街上等咖啡。", "能帮我把这几杯送过去吗？送给在街上的成员就行。"],
      active: ["咖啡还热着，快送过去！{hint}"],
      done: ["送到了？太好了。这顶帽子送你，以后来了就是熟客。"],
      after: ["今天也来一杯？"],
    },
    photographer: {
      name: "Aiko · 摄影师",
      offer: ["我在拍一组「悉尼的周四」明信片。", "港口有几个取景点，Kirribilli 那边能把歌剧院和大桥装进一张。帮我拍几张？"],
      active: ["{hint} 取景点上会有相机图标。"],
      done: ["拍得真好。这顶贝雷帽送你——以后你就是摄影师了。"],
      after: ["光线好的时候，再去 Kirribilli 看看。"],
    },
    tourist: {
      name: "Ben · 游客",
      offer: ["一只白鹮把我的薯条叼走了！它们在这儿叫「垃圾桶鸡」……", "你能去跟它们交个朋友吗？说不定它会还我一根。"],
      active: ["{hint}"],
      done: ["它居然跟着你走了！行吧，薯条送它了。这顶毛线帽给你。"],
      after: ["我再也不在码头边上吃薯条了。"],
    },
    greeter: {
      name: "Lulu · Luna Park",
      offer: ["悉尼人见面就一句 G'day。", "去跟路上的人打个招呼吧——五个就行，我给你准备了考拉耳朵。"],
      active: ["{hint}"],
      done: ["看吧，大家都挺友好的。考拉耳朵是你的了！"],
      after: ["G'day！"],
    },
    hunter: {
      name: "Theo · 碎片猎人",
      offer: ["这座城里藏着会发光的 Vibe 碎片。", "码头尽头、桥下、公园角落……我帮你盯着，屏幕边上的箭头会指向最近的一块。找八块回来。"],
      active: ["{hint}"],
      done: ["八块！你比我还会找。剩下的，就靠你自己了。"],
      after: ["听说 Chatswood 那边也有几块。"],
    },
  },

  member: {
    hello: "打个招呼",
    met: "已经打过招呼",
    card: "查看完整成员卡",
    looking: "在找",
    help: "能帮",
    builds: "在做",
    roles: {
      builder: "在做产品",
      business: "做生意",
      advisor: "顾问",
      creator: "做内容",
      organiser: "组织者",
      listener: "来听听",
    },
    guest: "游客",
    guestNote: "游客还没有成员卡。",
    you: "这是你",
    claim: "认领我的成员卡",
  },

  stall: {
    by: "作者",
    visit: "打开看看",
    maker: "作者名片",
    stages: {
      idea: "💡 想法",
      local: "🛠 本地能跑",
      beta: "🧪 内测中",
      live: "🚀 已上线",
      revenue: "💰 已有收入",
    },
    placeholder: "你的摊位",
    placeholderNote: "把你做的东西挂到成员卡上，就会在这里摆一个摊。",
  },

  train: {
    title: "T1 北岸线",
    toChatswood: "开往 Chatswood",
    toCity: "开往 Milsons Point",
    next: "下一站：{name}",
    arriving: "{name} 到了",
    skip: "跳过",
    doors: "请注意，车门即将开启",
  },

  ferry: {
    title: "渡轮",
    toMilsons: "去 Milsons Point",
    toQuay: "回环形码头",
    sailing: "渡轮开过海港……",
  },

  landmarks: {
    quay: { name: "环形码头 Circular Quay", fact: "悉尼的渡轮枢纽。绿黄相间的渡轮从这里开往全港。" },
    opera: { name: "悉尼歌剧院", fact: "丹麦建筑师约恩·伍重设计，1973 年启用，2007 年列入世界遗产。" },
    customs: { name: "海关大楼 Customs House", fact: "悉尼的老海关大楼，如今里面是一座公共图书馆。" },
    mca: { name: "当代艺术博物馆 MCA", fact: "环形码头西侧那栋 Art Deco 大楼。" },
    rocks: { name: "The Rocks · Cadmans Cottage", fact: "1816 年建成，悉尼现存最古老的建筑之一。" },
    pylon: { name: "桥塔观景台 Pylon Lookout", fact: "藏在大桥东南桥塔里的观景台，爬两百来级台阶上去。" },
    bridge: { name: "海港大桥", fact: "1932 年通车，悉尼人叫它「衣架」The Coathanger。" },
    luna: { name: "Luna Park", fact: "1935 年开的游乐园，入口是那张咧嘴大笑的巨脸。" },
    milsons: { name: "Milsons Point 车站", fact: "大桥北端的车站，T1 北岸线从这里往北。" },
    kirribilli: { name: "Kirribilli", fact: "海港北岸的半岛，总理在悉尼的官邸 Kirribilli House 就在这里。" },
    garden: { name: "皇家植物园", fact: "1816 年建园，澳洲最古老的科研机构。" },
    station: { name: "Chatswood 车站", fact: "T1 北岸线火车和悉尼地铁在这里交汇。" },
    mall: { name: "Chatswood Mall", fact: "Victoria Avenue 的步行街，周四有集市。" },
    concourse: { name: "The Concourse", fact: "Chatswood 的剧院、音乐厅和图书馆都在这里。" },
    avenue: { name: "The Avenue · Vibe Thursday", fact: "465 Victoria Avenue。每周四上午 10:30，那张桌子就在这儿。" },
    oval: { name: "Chatswood Oval", fact: "街区里的一片大草坪。春天小心喜鹊俯冲。" },
  },

  critters: {
    ibis: { name: "澳洲白鹮", fact: "外号「垃圾桶鸡」bin chicken。悉尼城里到处都是，专翻垃圾桶。" },
    gull: { name: "银鸥", fact: "码头上等你手里薯条的那位。" },
    cockatoo: { name: "葵花鹦鹉", fact: "硫冠凤头鹦鹉。悉尼一些街区的鹦鹉学会了自己掀开垃圾桶盖。" },
    lorikeet: { name: "彩虹吸蜜鹦鹉", fact: "吃花蜜和花粉，傍晚成群飞过，吵得很。" },
    kookaburra: { name: "笑翠鸟", fact: "世界上最大的翠鸟，叫声像人在大笑。" },
    dragon: { name: "东部水龙", fact: "植物园里常见，趴在石头上晒太阳。" },
    turkey: { name: "灌丛火鸡", fact: "雄鸟会用落叶堆出巨大的土丘当巢，北岸人家的花园常被它刨平。" },
    magpie: { name: "澳洲喜鹊", fact: "春天是它的俯冲季。它们记得住人脸。" },
    whale: { name: "座头鲸", fact: "春天北上洄游经过悉尼外海，偶尔会游进港里。" },
    golden: { name: "金色白鹮", fact: "只在周四出现。现实里没有这种鸟——但周四是真的。" },
  },

  befriend: {
    title: "慢慢靠近……",
    tap: "指针落在绿色区域时点一下",
    tapButton: "现在！",
    success: "它愿意跟你做朋友了！",
    fail: "它被吓跑了一点点。再试一次？",
    retry: "再试一次",
    leave: "算了",
    already: "你们已经是朋友了。",
  },

  bag: {
    title: "收集",
    stamps: "地标印章",
    critters: "悉尼动物图鉴",
    shards: "Vibe 碎片",
    unknown: "？？？",
    progress: "{n}/{total}",
  },

  wardrobe: {
    title: "衣柜",
    hat: "帽子",
    pet: "宠物",
    none: "无",
    locked: "未解锁",
    petHint: "交到朋友的动物可以跟着你走。",
    hats: {
      none: "不戴",
      bucket: "渔夫帽",
      akubra: "Akubra 牛仔帽",
      crest: "鹦鹉冠",
      sail: "歌剧院帆冠",
      lime: "周四青柠帽",
      jacaranda: "蓝花楹花环",
      cup: "咖啡杯帽",
      beanie: "白鹮毛线帽",
      beret: "摄影师贝雷帽",
      koala: "考拉耳朵",
    },
    unlock: {
      none: "",
      bucket: "完成「你在做什么」",
      akubra: "集齐 8 个印章",
      crest: "交到 5 个动物朋友",
      sail: "找齐所有 Vibe 碎片",
      lime: "完成主线",
      jacaranda: "连续 3 天来玩",
      cup: "完成支线「咖啡跑腿」",
      beanie: "完成支线「薯条大盗」",
      beret: "完成支线「寄往周四的明信片」",
      koala: "完成支线「G'day 挑战」",
    },
  },

  emotes: {
    wave: "打招呼",
    heart: "喜欢",
    laugh: "哈哈",
    coffee: "喝咖啡",
    idea: "有想法",
    party: "庆祝",
    chat: "聊聊？",
    thanks: "谢谢",
    gday: "G'day",
    building: "在做什么",
    thursday: "周四见",
    follow: "跟我来",
    nice: "漂亮",
    coffeeq: "喝咖啡",
    help: "帮忙",
    bye: "回头见",
  },

  guestAnimals: ["白鹮", "银鸥", "葵花鹦鹉", "吸蜜鹦鹉", "笑翠鸟", "水龙", "火鸡", "喜鹊", "袋鼠", "考拉"],
  guestName: "游客·{animal}{n}",

  controls: {
    title: "怎么玩",
    phone: "手机：左下方向键走路，或者直接点地面；右下 A 键对话、互动。",
    keys: "电脑：方向键 / WASD 走路，空格或 E 互动，Esc 关闭窗口。",
    ok: "知道了",
  },

  guide: {
    chapter: "第 {n} 章",
    meters: "{m} 米",
    otherMap: "先去{place}",
    station: "车站",
    track: "追踪",
    tracking: "追踪中",
    main: "主线",
    side: "支线",
    daily: "今日任务",
    dailyNote: "每天悉尼时间零点换一批，所有玩家今天都是同样三件。",
    stars: "已完成每日任务 {n} 个",
    allDaily: "今天三件都做完了！",
    dailyDone: "每日任务完成 ★",
  },

  side: {
    accept: "好，交给我",
    decline: "下次吧",
    reward: "奖励：{hat}",
    finished: "支线完成：{name}",
    ready: "「{name}」目标达成——回去找 {who}",
    returnTo: "回去找 {who} 交任务。",
    quests: {
      ibis: { title: "薯条大盗", hint: "在码头附近找到一只白鹮，跟它交朋友（{have}/{need}）。" },
      postcards: { title: "寄往周四的明信片", hint: "在港口的取景点拍 {need} 张明信片（{have}/{need}）。" },
      shards: { title: "碎片猎人", hint: "找到 {need} 块 Vibe 碎片——箭头会指向最近的一块（{have}/{need}）。" },
      gday: { title: "G'day 挑战", hint: "跟 {need} 个路人打招呼（{have}/{need}）。" },
      coffee: { title: "咖啡跑腿", hint: "把咖啡送给 {need} 位 Chatswood 的成员（{have}/{need}）。" },
    },
  },

  daily: {
    critter: "逗一逗任意一只动物",
    greet: "跟 {need} 个路人打招呼",
    landmark: "去一趟：{place}",
    phrase: "用快捷短语跟人说句话",
    photo: "拍一张明信片",
    member: "跟一位成员聊聊",
  },

  phrases: {
    gday: "G'day！",
    building: "你在做什么？",
    thursday: "周四见！",
    follow: "跟我来！",
    nice: "做得漂亮！",
    coffeeq: "喝杯咖啡？",
    help: "能帮我一下吗？",
    bye: "回头见！",
  },

  walkers: [
    "G'day！",
    "今天天气真好，适合坐渡轮。",
    "你也是去 Chatswood 的吗？",
    "那边有只白鹮在翻垃圾桶……",
    "听说周四上午有个 AI 局？",
    "来杯 flat white 吗？",
    "别在草坪上躺太久，春天喜鹊会俯冲。",
    "歌剧院的台阶上看日落最好。",
    "我刚在集市买了个小东西，挺有意思。",
    "走桥过去大概二十分钟。",
  ],

  barks: {
    deckhand: "渡轮快开了——有事找我！",
    busker: "（弹着吉他）……来听一首？",
    climber: "桥上风大，抓稳帽子。",
    guard: "T1 往北，下一班马上到。",
    stallholder: "周四集市，走过路过！",
    host: "10:30 了，大家陆续到了。",
    noticeboard: "",
    barista: "新鲜的 flat white！",
    photographer: "这光线，太适合拍照了。",
    tourist: "我的薯条！！",
    greeter: "欢迎来 Luna Park！",
    hunter: "你看见闪光的东西了吗？",
  },

  photo: {
    spot: "取景点",
    take: "拍明信片",
    title: "明信片",
    save: "保存图片",
    shareHint: "长按或点「保存图片」，可以发给朋友。",
    withPeer: "合影",
    spots: {
      forecourt: "歌剧院前庭",
      kirribilli: "Kirribilli · 看歌剧院和大桥",
      lunapark: "Luna Park 门口",
      farmcove: "Farm Cove",
      mall: "Chatswood Mall",
    },
  },

  social: {
    highFive: "和 {name} 击掌！",
    greetedWalker: "你向路人打了招呼",
    friends: "遇到过的玩家",
    noFriends: "还没有。向附近的玩家挥手、击掌或者合影，就会记在这里。",
    highFives: "击掌 {n} 次",
    ask: "问问 TA 在做什么",
    giveCoffee: "送一杯咖啡",
    coffeeThanks: "谢谢咖啡！",
    quickChat: "快捷短语",
  },

  music: {
    on: "音乐：开",
    off: "音乐：关",
  },

  back: "回首页",
};

export type GameCopy = typeof zh;

const en: GameCopy = {
  meta: {
    title: "Sydney Thursday Quest · a pixel game · Vibe Thursday",
    description:
      "A pixel Sydney: walk from Circular Quay to the Opera House, cross the Harbour Bridge on foot, ride the North Shore line to Chatswood, browse what the community built at the Thursday market, and make the 10:30 table. Multiplayer, and it works on a phone.",
  },
  title: "Sydney Thursday Quest",
  subtitle: "Vibe Thursday · a pixel RPG",
  tagline: "The streets come from a real map. Walk to the Opera House, cross the bridge, take the train to Chatswood, and find the table at 10:30 on Thursday.",
  start: "Start",
  continue: "Continue",
  newGame: "New game",
  loading: "Laying out Sydney's streets…",
  osm: "Map data © OpenStreetMap contributors",
  saveNote: "Progress is saved in this device's browser.",

  create: {
    title: "Who are you?",
    hint: "Anything goes — you can change it later in the wardrobe.",
    skin: "Skin",
    hair: "Hair",
    hairColor: "Hair colour",
    top: "Top",
    bottom: "Bottom",
    acc: "Extra",
    go: "Off to Circular Quay",
    random: "Random",
  },

  hud: {
    online: "{n} online",
    offline: "Offline",
    quest: "Quest",
    bag: "Collection",
    wardrobe: "Wardrobe",
    emote: "Emote",
    map: "Map",
    close: "Close",
    a: "A",
    talk: "Talk",
    look: "Look",
    board: "Board",
    ferry: "Ferry",
    read: "Read",
    befriend: "Befriend",
    visit: "Browse",
    you: "You",
    here: "You are here",
    streak: "{n}-day streak",
    thursday: "It's Thursday! The golden ibis is out",
    done: "Story complete",
  },

  toast: {
    stamp: "Stamped: {name}",
    shard: "Found a Vibe shard ({n}/{total})",
    critter: "New friend: {name}",
    hat: "New hat unlocked: {name}",
    quest: "Quest complete: {name}",
    streak: "Day {n} in a row in Sydney",
    joined: "{name} arrived",
    tooFar: "Too far — walk a bit closer first",
    saved: "Saved",
    rejoin: "Reconnected",
  },

  quests: {
    arrive: { title: "First words at the Quay", hint: "Find Mina the deckhand at Circular Quay." },
    muse: { title: "What are you making?", hint: "Head to the Opera House steps and find the busker." },
    wharf: { title: "The Wharf's noticeboard", hint: "Back at Circular Quay, read what people are stuck on ({have}/{need})." },
    bridge: { title: "Over the Coathanger", hint: "Walk north across the Harbour Bridge to Milsons Point station." },
    train: { title: "The North Shore line", hint: "Take the T1 from Milsons Point to Chatswood." },
    market: { title: "The Thursday market", hint: "Browse {need} stalls at the Chatswood Mall market ({have}/{need})." },
    people: { title: "Find your people", hint: "Say hello to {need} members around Chatswood ({have}/{need})." },
    thursday: { title: "Thursday, 10:30am", hint: "Get to The Avenue, 465 Victoria Avenue — the round building." },
    allDone: "Story complete. Fill the critter book, the stamps and the shards — or come to a real Thursday.",
  },

  ideas: {
    app: "An app or a website",
    content: "Content / media",
    shop: "A business",
    automation: "Automation / workflows",
  },

  npc: {
    deckhand: {
      name: "Mina · deckhand",
      first: [
        "Welcome to Circular Quay! The green-and-gold boats are Sydney's ferries — the whole harbour leaves from here.",
        "Came to Sydney with half an idea? Everybody does.",
        "Go up to the Opera House steps first. There's a busker who asks everyone the same question.",
      ],
      later: ["Want the other side? Tap the ferry sign on the wharf and it'll take you to Milsons Point.", "Next: {hint}"],
    },
    busker: {
      name: "Leo · busker",
      ask: ["(a few bars of guitar)… Hey. What are you making?"],
      reply: {
        app: "An app! A version people can tap beats a ten-page plan.",
        content: "People who make content understand people. You'll find your first readers at that Thursday table.",
        shop: "A business! Owners who use AI are rarer than people who code.",
        automation: "Automation — making an annoying job something you never think about again. Best place to start.",
      },
      after: ["Go back to the Quay and look at the noticeboard. People pin up whatever they're stuck on.", "{hint}"],
    },
    climber: {
      name: "Sam · bridge climber",
      lines: [
        "This bridge opened in 1932. Sydney calls it the Coathanger.",
        "The footpath runs all the way to the North Shore. At the end is Milsons Point station — the T1 goes to Chatswood.",
      ],
    },
    guard: {
      name: "Priya · station staff",
      lines: ["T1 North Shore line: six stops north to Chatswood — North Sydney, Waverton, Wollstonecraft, St Leonards, Artarmon, then you're there."],
      board: "Board for Chatswood",
      stay: "Not yet",
    },
    stallholder: {
      name: "Grace · stallholder",
      lines: [
        "Chatswood Mall has a market every Thursday.",
        "Today's stalls are a bit special: everything on them was built by someone from the Thursday table. Have a browse.",
      ],
      empty: "No stalls up yet — once members hang their work on their cards, stalls appear here.",
    },
    host: {
      name: "Host",
      lines: [
        "You found it! This is it: The Avenue, 465 Victoria Avenue — the round building on Brown and Railway Streets.",
        "Every Thursday at 10:30am, a table of people who build things, talking about what they're doing with AI and where they're stuck.",
        "Show something if you want to, or just listen. Free, no tickets.",
      ],
      demo: "Your turn. How do you want to share what you're making?",
      demoChoices: ["Open the laptop and demo it", "Talk about where I'm stuck", "Listen first"],
      demoReply: [
        "The screen lights up and three people lean in. Someone asks: is this live yet?",
        "You've barely finished saying where you're stuck when someone says: been there — let's talk after.",
        "You listen all morning and fill half a page. At the end someone asks: want to share next week?",
      ],
      ending: "That's a Thursday. The table in the game ends here — the real one is there every week.",
      signup: "Sign up for Thursday",
      claim: "Claim my member card",
      wharf: "Answer on the Wharf",
      later: ["Thursdays, 10:30am, The Avenue. See you next week."],
    },
    noticeboard: {
      name: "The Wharf noticeboard",
      intro: "People pin what they're stuck on here. Open one and read it — if you can help, answer it on the Wharf.",
      empty: "The board is empty today. Some examples:",
      examples: ["How does someone with no tech background start with AI?", "Six months of content and nothing's moving — what's wrong?", "Where does a small shop start going digital?"],
      by: "from {name}",
      example: "Example",
      open: "Answer on the Wharf",
    },
    barista: {
      name: "Nico · coffee cart",
      offer: ["Busy market today, and a few regulars are out on the street waiting on coffee.", "Could you run these over? Any member on the street will do."],
      active: ["Still hot — go go go! {hint}"],
      done: ["All delivered? Legend. Have a hat — you're a regular now."],
      after: ["Another one today?"],
    },
    photographer: {
      name: "Aiko · photographer",
      offer: ["I'm shooting a set of postcards: Sydney on a Thursday.", "There are a few spots on the harbour — from Kirribilli you get the Opera House and the bridge in one frame. Take a few for me?"],
      active: ["{hint} Look for the camera icons."],
      done: ["These are great. Take the beret — you're a photographer now."],
      after: ["Try Kirribilli again when the light's good."],
    },
    tourist: {
      name: "Ben · tourist",
      offer: ["An ibis just nicked my chips! They call them bin chickens here…", "Could you go and make friends with one? Maybe it'll give one back."],
      active: ["{hint}"],
      done: ["It's following you around! Fine, it can keep the chips. Have this beanie."],
      after: ["Never eating chips by the water again."],
    },
    greeter: {
      name: "Lulu · Luna Park",
      offer: ["In Sydney it's G'day, every time.", "Go and say it to people on the street — five of them — and the koala ears are yours."],
      active: ["{hint}"],
      done: ["See? Friendly lot. Koala ears, as promised!"],
      after: ["G'day!"],
    },
    hunter: {
      name: "Theo · shard hunter",
      offer: ["There are glowing Vibe shards hidden all over this city.", "Ends of wharves, under the bridge, corners of parks… I'll keep watch — the arrow at the edge of your screen points at the nearest. Bring back eight."],
      active: ["{hint}"],
      done: ["Eight! You're better at this than me. The rest are yours to find."],
      after: ["Word is there are a few in Chatswood too."],
    },
  },

  member: {
    hello: "Say hello",
    met: "Already said hello",
    card: "See their full card",
    looking: "Looking for",
    help: "Can help with",
    builds: "Building",
    roles: {
      builder: "Builds products",
      business: "Runs a business",
      advisor: "Advisor",
      creator: "Makes content",
      organiser: "Organiser",
      listener: "Here to listen",
    },
    guest: "Guest",
    guestNote: "Guests don't have a member card yet.",
    you: "That's you",
    claim: "Claim my member card",
  },

  stall: {
    by: "by",
    visit: "Open it",
    maker: "Maker's card",
    stages: {
      idea: "💡 Idea",
      local: "🛠 Runs locally",
      beta: "🧪 In beta",
      live: "🚀 Live",
      revenue: "💰 Earning",
    },
    placeholder: "Your stall",
    placeholderNote: "Hang what you've built on your member card and it gets a stall here.",
  },

  train: {
    title: "T1 North Shore line",
    toChatswood: "to Chatswood",
    toCity: "to Milsons Point",
    next: "Next stop: {name}",
    arriving: "Now arriving: {name}",
    skip: "Skip",
    doors: "Doors opening",
  },

  ferry: {
    title: "Ferry",
    toMilsons: "To Milsons Point",
    toQuay: "Back to Circular Quay",
    sailing: "Crossing the harbour…",
  },

  landmarks: {
    quay: { name: "Circular Quay", fact: "Sydney's ferry hub. The green-and-gold ferries leave from here for the whole harbour." },
    opera: { name: "Sydney Opera House", fact: "Designed by Jørn Utzon, opened in 1973, World Heritage listed in 2007." },
    customs: { name: "Customs House", fact: "Sydney's old customs house — a public library inside today." },
    mca: { name: "Museum of Contemporary Art", fact: "The Art Deco building on the west side of the Quay." },
    rocks: { name: "The Rocks · Cadmans Cottage", fact: "Built in 1816 — one of the oldest surviving buildings in Sydney." },
    pylon: { name: "Pylon Lookout", fact: "A lookout inside the bridge's south-east pylon, a couple of hundred steps up." },
    bridge: { name: "Sydney Harbour Bridge", fact: "Opened in 1932. Locals call it the Coathanger." },
    luna: { name: "Luna Park", fact: "Open since 1935. You walk in through the giant grinning face." },
    milsons: { name: "Milsons Point station", fact: "At the bridge's north end. The T1 North Shore line heads north from here." },
    kirribilli: { name: "Kirribilli", fact: "The harbour's north-shore point — Kirribilli House, the Prime Minister's Sydney residence, is here." },
    garden: { name: "Royal Botanic Garden", fact: "Founded in 1816 — Australia's oldest scientific institution." },
    station: { name: "Chatswood station", fact: "Where the T1 North Shore line meets the Sydney Metro." },
    mall: { name: "Chatswood Mall", fact: "Victoria Avenue's pedestrian mall, with a market on Thursdays." },
    concourse: { name: "The Concourse", fact: "Chatswood's theatre, concert hall and library, all in one place." },
    avenue: { name: "The Avenue · Vibe Thursday", fact: "465 Victoria Avenue. Thursdays at 10:30am, the table is here." },
    oval: { name: "Chatswood Oval", fact: "A big green in the middle of the streets. Watch for swooping magpies in spring." },
  },

  critters: {
    ibis: { name: "Australian white ibis", fact: "Nicknamed the bin chicken. All over the city, going through the bins." },
    gull: { name: "Silver gull", fact: "The one on the wharf waiting for your chips." },
    cockatoo: { name: "Sulphur-crested cockatoo", fact: "In some Sydney suburbs they've learned to flip open wheelie-bin lids." },
    lorikeet: { name: "Rainbow lorikeet", fact: "Lives on nectar and pollen; flies over in loud flocks at dusk." },
    kookaburra: { name: "Laughing kookaburra", fact: "The world's biggest kingfisher, with a call like someone laughing." },
    dragon: { name: "Eastern water dragon", fact: "A regular in the Botanic Garden, sunning itself on the rocks." },
    turkey: { name: "Australian brush turkey", fact: "Males rake leaf litter into huge nesting mounds — North Shore gardens know it well." },
    magpie: { name: "Australian magpie", fact: "Spring is swooping season. They remember faces." },
    whale: { name: "Humpback whale", fact: "Migrates past Sydney in spring, and now and then swims into the harbour." },
    golden: { name: "Golden ibis", fact: "Only shows up on Thursdays. Not a real bird — but Thursday is." },
  },

  befriend: {
    title: "Easy does it…",
    tap: "Tap when the marker is in the green",
    tapButton: "Now!",
    success: "It wants to be friends!",
    fail: "It startled a little. Try again?",
    retry: "Try again",
    leave: "Leave it",
    already: "You're already friends.",
  },

  bag: {
    title: "Collection",
    stamps: "Landmark stamps",
    critters: "Sydney critters",
    shards: "Vibe shards",
    unknown: "???",
    progress: "{n}/{total}",
  },

  wardrobe: {
    title: "Wardrobe",
    hat: "Hat",
    pet: "Pet",
    none: "None",
    locked: "Locked",
    petHint: "Critters you've befriended can follow you around.",
    hats: {
      none: "No hat",
      bucket: "Bucket hat",
      akubra: "Akubra",
      crest: "Cockatoo crest",
      sail: "Opera sail crown",
      lime: "Thursday lime cap",
      jacaranda: "Jacaranda crown",
      cup: "Coffee-cup hat",
      beanie: "Ibis beanie",
      beret: "Photographer's beret",
      koala: "Koala ears",
    },
    unlock: {
      none: "",
      bucket: "Finish “What are you making?”",
      akubra: "Collect 8 stamps",
      crest: "Befriend 5 critters",
      sail: "Find every Vibe shard",
      lime: "Finish the story",
      jacaranda: "Play 3 days in a row",
      cup: "Finish “Coffee run”",
      beanie: "Finish “The chip thief”",
      beret: "Finish “Postcards to Thursday”",
      koala: "Finish “The G'day challenge”",
    },
  },

  emotes: {
    wave: "Wave",
    heart: "Love it",
    laugh: "Haha",
    coffee: "Coffee",
    idea: "Idea",
    party: "Celebrate",
    chat: "Chat?",
    thanks: "Thanks",
    gday: "G'day",
    building: "Building?",
    thursday: "Thursday",
    follow: "Follow",
    nice: "Nice",
    coffeeq: "Coffee?",
    help: "Help?",
    bye: "Later",
  },

  guestAnimals: ["Ibis", "Gull", "Cockatoo", "Lorikeet", "Kookaburra", "Dragon", "Turkey", "Magpie", "Roo", "Koala"],
  guestName: "{animal} {n}",

  controls: {
    title: "How to play",
    phone: "Phone: the pad bottom-left walks, or tap the ground; the A button bottom-right talks and interacts.",
    keys: "Keyboard: arrows / WASD to walk, Space or E to interact, Esc to close.",
    ok: "Got it",
  },

  guide: {
    chapter: "Chapter {n}",
    meters: "{m} m",
    otherMap: "Head to the {place} first",
    station: "station",
    track: "Track",
    tracking: "Tracking",
    main: "Story",
    side: "Side quests",
    daily: "Today",
    dailyNote: "A new three every midnight Sydney time — the same three for everybody playing.",
    stars: "{n} daily tasks done",
    allDaily: "All three done today!",
    dailyDone: "Daily task done ★",
  },

  side: {
    accept: "Leave it with me",
    decline: "Maybe later",
    reward: "Reward: {hat}",
    finished: "Side quest complete: {name}",
    ready: "“{name}” done — go back to {who}",
    returnTo: "Go back to {who} to finish.",
    quests: {
      ibis: { title: "The chip thief", hint: "Find an ibis around the Quay and make friends with it ({have}/{need})." },
      postcards: { title: "Postcards to Thursday", hint: "Take {need} postcards at the harbour's photo spots ({have}/{need})." },
      shards: { title: "Shard hunter", hint: "Find {need} Vibe shards — the arrow points to the nearest ({have}/{need})." },
      gday: { title: "The G'day challenge", hint: "Say g'day to {need} passers-by ({have}/{need})." },
      coffee: { title: "Coffee run", hint: "Take coffee to {need} members around Chatswood ({have}/{need})." },
    },
  },

  daily: {
    critter: "Say hello to any critter",
    greet: "Say g'day to {need} passers-by",
    landmark: "Pay a visit: {place}",
    phrase: "Say something with a quick-chat phrase",
    photo: "Take a postcard",
    member: "Have a chat with a member",
  },

  phrases: {
    gday: "G'day!",
    building: "What are you building?",
    thursday: "See you Thursday!",
    follow: "Follow me!",
    nice: "Nice one!",
    coffeeq: "Coffee?",
    help: "Can you help?",
    bye: "Catch you later!",
  },

  walkers: [
    "G'day!",
    "Lovely day for a ferry ride.",
    "Heading to Chatswood too?",
    "There's an ibis going through the bins over there…",
    "Heard there's an AI meetup on Thursday mornings?",
    "Fancy a flat white?",
    "Don't lie on the grass too long — magpies swoop in spring.",
    "The Opera House steps are the spot for sunset.",
    "Just picked up something neat at the market.",
    "About twenty minutes to walk the bridge.",
  ],

  barks: {
    deckhand: "Ferry's about to go — give us a shout!",
    busker: "(strumming) …fancy a song?",
    climber: "Windy up here. Hold onto your hat.",
    guard: "T1 northbound, next one's due.",
    stallholder: "Thursday market, come have a look!",
    host: "10:30 — people are arriving.",
    noticeboard: "",
    barista: "Fresh flat whites!",
    photographer: "Look at this light.",
    tourist: "My chips!!",
    greeter: "Welcome to Luna Park!",
    hunter: "Seen anything glinting?",
  },

  photo: {
    spot: "Photo spot",
    take: "Take a postcard",
    title: "Postcard",
    save: "Save image",
    shareHint: "Long-press or tap “Save image” to send it to someone.",
    withPeer: "Photo together",
    spots: {
      forecourt: "Opera House forecourt",
      kirribilli: "Kirribilli · Opera House and bridge",
      lunapark: "Luna Park gates",
      farmcove: "Farm Cove",
      mall: "Chatswood Mall",
    },
  },

  social: {
    highFive: "High five with {name}!",
    greetedWalker: "You said g'day",
    friends: "Players you've met",
    noFriends: "Nobody yet. Wave, high-five or take a photo with a player nearby and they'll be noted here.",
    highFives: "{n} high fives",
    ask: "Ask what they're building",
    giveCoffee: "Give them a coffee",
    coffeeThanks: "Thanks for the coffee!",
    quickChat: "Quick chat",
  },

  music: {
    on: "Music: on",
    off: "Music: off",
  },

  back: "Home",
};

export const GAME_COPY = { zh, en };

/** Fills `{name}` placeholders. Missing values are left as they are. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => (key in values ? String(values[key]) : match));
}
