// Relative, not "@/": the tests load this through Node's type stripper, which
// does not read tsconfig's path aliases.
import { FIRST_SESSION_DATE } from "./sessions.ts";

/**
 * Which card this week's poster is.
 *
 * The poster that goes into the WeChat group used to be the same drawing every
 * week with different words in it, which is a notice. This turns it into one of
 * a set: every Thursday gets its own Sydney picture, its own tint, and a serial
 * number printed on it, so the ones somebody kept are a collection rather than
 * eight copies of a notice.
 *
 * ★ Everything here is derived from the session's date, and from where the
 * series is counted from. Same Thursday, same card, every time it is drawn —
 * on the organiser's phone, on a laptop, and again next year. That is the whole
 * reason there is no randomness at the point of drawing: a collectible that
 * changes when you redraw it is not a collectible, and "重画一张" is a button
 * somebody presses.
 *
 * ⚠️ The second input is `FIRST_SESSION_DATE`, which reads `process.env
 * .FIRST_SESSION_DATE` (`sessions.ts`). Moving it renumbers every card
 * retroactively and shifts which picture and tint each Thursday gets — while
 * the seed, hashed from the date alone, stays put. NO.08 would come back as a
 * different picture carrying the same small details. That env var is a
 * launch-date setting and nothing else should ever touch it.
 *
 * No canvas and no DOM in this file, so the tests can walk a year of Thursdays
 * without a browser.
 */

/** The Sydney pictures, in the order they come round. */
export const SCENES = [
  { id: "harbour", en: "HARBOUR BRIDGE", zh: "海港大桥" },
  { id: "opera", en: "OPERA HOUSE", zh: "歌剧院" },
  { id: "chatswood", en: "CHATSWOOD", zh: "车士活的塔" },
  { id: "wharf", en: "THE WHARF", zh: "码头与海鸥" },
  { id: "bondi", en: "BONDI", zh: "邦迪的浪" },
  { id: "ferry", en: "HARBOUR FERRY", zh: "海港渡轮" },
  { id: "tower", en: "SYDNEY TOWER", zh: "悉尼塔" },
] as const;

export type SceneId = (typeof SCENES)[number]["id"];

export type Scene = (typeof SCENES)[number];

/**
 * Where a scene's picture lives, under `public/`.
 *
 * Derived from the id rather than stored next to it: the two would be a pair
 * of strings that have to agree, and the failure when they stop agreeing is a
 * card that draws with no picture and says nothing about it. Generated by
 * `scripts/card-art.mjs`; `tests/poster-card.test.mts` checks every scene has
 * a file actually sitting there.
 */
export function cardArt(scene: Scene | SceneId): string {
  return `/cards/${typeof scene === "string" ? scene : scene.id}.png`;
}

/**
 * Which of the site's three accents inks the picture.
 *
 * Only the picture. The text keeps its fixed roles — lime for the time, cyan
 * for the eyebrow, yellow for the Wharf heading — because a poster where the
 * meaning of a colour changes week to week is not a series, it is three
 * different posters.
 */
export const TINTS = ["accent", "spark", "chip"] as const;
export type Tint = (typeof TINTS)[number];

export type PosterCard = {
  /** The serial printed on the card, 1-based. */
  no: number;
  scene: Scene;
  tint: Tint;
  /** Feeds `rng`, for the details that differ week to week. */
  seed: number;
};

const DAY = 24 * 60 * 60 * 1000;

/**
 * Which week of the series a session is, counting the first one as 1.
 *
 * ⚠️ Arithmetic from the launch date, not a lookup: the poster is drawn for a
 * session that has not happened, and the only list of sessions this site keeps
 * — the write-ups in `content.ts` — necessarily stops at the last one that did.
 *
 * The consequence, stated rather than discovered later: if a Thursday is ever
 * skipped, this keeps counting weeks while the archive's own index counts
 * sessions, and the two numbers part company. A card is an issue number, so
 * counting weeks is the behaviour to want here — but if they ever need to
 * agree, this is the line that has to change.
 */
export function cardNumber(session: string, firstSession: string = FIRST_SESSION_DATE): number {
  const weeks = Math.round(
    (Date.parse(`${session}T00:00:00Z`) - Date.parse(`${firstSession}T00:00:00Z`)) / (7 * DAY),
  );

  // A card numbered zero or less is meaningless; it can only come from a date
  // before the meetup existed, which is never a date a poster is drawn for.
  return Math.max(1, weeks + 1);
}

/**
 * Hashes the date string into a seed.
 *
 * xmur3, chosen because it is four lines and mixes well enough that two
 * consecutive Thursdays — one character apart — do not produce visibly related
 * pictures, which a sum-of-characters hash would.
 */
export function seedFrom(text: string): number {
  let h = 2166136261;

  for (let i = 0; i < text.length; i += 1) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }

  // >>> 0 keeps it an unsigned 32-bit value; mulberry32 below assumes that.
  return h >>> 0;
}

/**
 * mulberry32: a small deterministic PRNG returning [0, 1).
 *
 * Deliberately not `Math.random`. Every wobble on the card — where the stars
 * are, which windows are lit, how the water moves — comes from here, so the
 * card for a given Thursday is the same picture every time it is drawn.
 */
export function rng(seed: number): () => number {
  let state = seed >>> 0;

  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * The whole card, from the session's ISO date.
 *
 * Scene and tint step by one every week and their cycles are different lengths
 * (7 and 3), so the exact same card comes back only every 21 weeks — and even
 * then the seed is different, because it is hashed from the date rather than
 * from the number.
 */
export function posterCard(session: string, firstSession: string = FIRST_SESSION_DATE): PosterCard {
  const no = cardNumber(session, firstSession);

  return {
    no,
    scene: SCENES[(no - 1) % SCENES.length],
    tint: TINTS[(no - 1) % TINTS.length],
    seed: seedFrom(session),
  };
}
