import { ACCENT, alpha, CHIP, INK, SPARK } from "./canvas-kit";
import type { PosterCard, Tint } from "@/lib/poster-card";

/**
 * Laying the week's picture into the card, and the card's own edge.
 *
 * The picture itself is a file — one of seven Sydney plates under
 * `public/cards/`, generated by `scripts/card-art.mjs` and picked by
 * `posterCard()`. This module only composites: it puts the plate down, keeps
 * the type on top of it readable, and draws the border.
 *
 * ★ These scenes used to be drawn here, as halftone silhouettes built from
 * canvas paths. It was the wrong tool, and the review said so with evidence:
 * of the seven, three came out as unrecognisable fields of dots, and two of
 * those were different landmarks that looked identical to each other. Plates
 * generated from one shared style spine get the subject right and — more to
 * the point — get all seven to look like one set, which is the thing a card
 * series lives or dies on.
 *
 * What survived from that version is the part worth keeping: the card's frame,
 * its corner ticks, and the discipline about where type is allowed to sit.
 */

/** The three accents, as the card's ink for its serial and its frame. */
const TINT: Record<Tint, string> = { accent: ACCENT, spark: SPARK, chip: CHIP };

/**
 * The strip holding the venue and the sign-up count.
 *
 * ⚠️ Measured, not guessed. Those two lines sit at y=382-428 and y=444-484
 * (`PosterExport` advances y by 62 and then 54 through them) and they are the
 * smallest, greyest type on the card. The review measured them at 3.9:1 over
 * the old backdrop — which passes as a contrast ratio and still could not be
 * read at thumbnail size, because the failure is interference rather than
 * contrast: a halftone dot pitch close to the stroke width of a Chinese glyph
 * interleaves with the character. The fix is not more contrast, it is holding
 * one band of the picture back.
 */
const TEXT_STRIP = { top: 360, bottom: 500 };

/**
 * Draws the week's plate, full bleed, with the scrims the type needs.
 *
 * ★ Full bleed is the point. The first version put its art in the top third
 * and ruled a line under it, which is a masthead — and the review named it as
 * exactly that. A card's picture is the card. There is no divider on this
 * poster any more: the picture gets quieter as it goes down, and the words sit
 * on it.
 */
export function drawCardImage(
  ctx: CanvasRenderingContext2D,
  art: HTMLImageElement,
  W: number,
  H: number,
): void {
  ctx.fillStyle = INK;
  ctx.fillRect(0, 0, W, H);

  // The plates are generated at exactly this ratio, so for the real asset this
  // is a 1:1 draw; `cover` is here so that a plate of some other size still
  // fills the card rather than leaving a band of bare ink down one side.
  const scale = Math.max(W / art.width, H / art.height);
  const w = art.width * scale;
  const h = art.height * scale;
  ctx.drawImage(art, (W - w) / 2, (H - h) / 2, w, h);

  // ── Down the page ────────────────────────────────────────────────
  // The lower half carries the questions, which are the half of this poster
  // worth having. The picture is asked to recede there, rather than the text
  // being asked to fight it.
  const depth = ctx.createLinearGradient(0, H * 0.34, 0, H);
  depth.addColorStop(0, alpha(INK, 0));
  depth.addColorStop(0.45, alpha(INK, 0.72));
  depth.addColorStop(1, alpha(INK, 0.93));
  ctx.fillStyle = depth;
  ctx.fillRect(0, H * 0.34, W, H * 0.66);

  // ── Across the page ──────────────────────────────────────────────
  // Every line is left-aligned, so the left is where the ink is needed and the
  // right is where the picture is allowed to stay a picture.
  const side = ctx.createLinearGradient(0, 0, W * 0.9, 0);
  side.addColorStop(0, alpha(INK, 0.66));
  side.addColorStop(0.55, alpha(INK, 0.3));
  side.addColorStop(1, alpha(INK, 0));
  ctx.fillStyle = side;
  ctx.fillRect(0, 0, W, H);

  // ── The two grey lines ───────────────────────────────────────────
  // A soft plate rather than a hard box: the strip has to stop interfering,
  // not announce that it has been protected.
  const strip = ctx.createLinearGradient(0, TEXT_STRIP.top, 0, TEXT_STRIP.bottom);
  strip.addColorStop(0, alpha(INK, 0));
  strip.addColorStop(0.28, alpha(INK, 0.82));
  strip.addColorStop(0.72, alpha(INK, 0.82));
  strip.addColorStop(1, alpha(INK, 0));
  ctx.fillStyle = strip;
  ctx.fillRect(0, TEXT_STRIP.top, W * 0.82, TEXT_STRIP.bottom - TEXT_STRIP.top);
}

/**
 * Bare ink, for the rare case where the week's plate will not load.
 *
 * The poster still has to come out. Everything that makes it worth pasting
 * into the group — the date, the questions, the code — is text drawn after
 * this, and none of it depends on the picture arriving.
 */
export function drawCardFallback(ctx: CanvasRenderingContext2D, W: number, H: number): void {
  ctx.fillStyle = INK;
  ctx.fillRect(0, 0, W, H);
}

/**
 * The frame that makes it a card rather than a picture: a hairline border and
 * four corner ticks in the week's tint.
 *
 * Inset 36px, which is half the page's padding — inside the bleed, outside
 * every line of type.
 */
export function drawCardFrame(ctx: CanvasRenderingContext2D, card: PosterCard, W: number, H: number): void {
  const ink = TINT[card.tint];
  const inset = 36;
  const r = 18;

  ctx.strokeStyle = alpha(ink, 0.24);
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.roundRect(inset, inset, W - inset * 2, H - inset * 2, r);
  ctx.stroke();

  // Corner ticks: two strokes at each corner, sitting on the border. Heavier
  // than the border on purpose — the review found them reading as a rendering
  // artefact while the two were the same weight.
  const arm = 34;
  ctx.strokeStyle = alpha(ink, 0.9);
  ctx.lineWidth = 5;

  for (const [x, sx] of [[inset, 1], [W - inset, -1]] as const) {
    for (const [y, sy] of [[inset, 1], [H - inset, -1]] as const) {
      ctx.beginPath();
      ctx.moveTo(x + sx * (r - 4), y);
      ctx.lineTo(x + sx * (r - 4 + arm), y);
      ctx.moveTo(x, y + sy * (r - 4));
      ctx.lineTo(x, y + sy * (r - 4 + arm));
      ctx.stroke();
    }
  }
}

/** The tint as a colour, for the card's serial number in the header. */
export function tintColor(card: PosterCard): string {
  return TINT[card.tint];
}
